config/routes.rb
Admission::Application.routes.draw do
  
 
  devise_for :users

  get "home/index"

  root :to => "home#index"

  resources :users do
      member do
        get 'application'
      end
    end
    
  match 'user_root' => 'users#move', as: :user_root

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :applicants do 
    member do
      get 'instance'
    end
    collection do
      get 'update_major_select'
      get 'get_semester'
    end
  end
  

end

app/models/applicant.rb
#Omnia Commenting to test git
class Applicant < ActiveRecord::Base
  belongs_to :user
  
  
  has_attached_file :photo,  :styles => {:original=>"500x500>" ,:medium => "300x300>", :thumb => "100x100>" }

  has_many :addresses, :dependent => :destroy, :order => "id ASC"
  has_one :admission_information, :dependent => :destroy
  has_many :secondary_schools, :dependent => :destroy, :order => "id ASC"
  has_many :colleges, :dependent => :destroy, :order => "id ASC"
  has_one :attachment, :dependent => :destroy
  has_many :guardians, :dependent => :destroy, :order => "id ASC"
  has_many :healths, :dependent => :destroy, :order => "id ASC"
  has_one :uni_related_info, :dependent => :destroy
  
  before_validation :atleast_one
  validates :first_name, :middle_name,:last_name,:date_of_birth, :place_of_birth, :gender, :transportation, :presence => true
  validates :first_name, :format => {:with => /^[a-zA-Z]+$/, :message => "first name contains non alphabetical characters"}
  validates :middle_name,  :format => {:with => /^[a-zA-Z]+$/, :message => "middle name contains non alphabetical characters"}
  validates :last_name, :format => {:with => /^[a-zA-Z]+$/, :message => "last name contains non alphabetical characters"}
  validates :place_of_birth, :format => {:with => /^\w+[^\d]\,\s*\w+[^\d]$/, :message => "Place of Birth contains non alphabetical characters or not in the format City, Country"}
  validates_date :passport_expiry_date, :after => lambda { Date.current } , :allow_blank => true
  
  #validates_attachment_presence :photo
  #validates_attachment_content_type :photo, :content_type=>['image/jpeg', 'image/png', 'image/gif'], :message => 'Image must be of type jpeg, png or gif'
  validates_date :date_of_birth, :passport_expiry_date, :allow_blank => true

  validates_inclusion_of :gender, :in => ["Female", "Male"]
  #validates_inclusion_of :military_status, :in => ["Completed", "Exempted","Postponed", "Does not apply"]
  validates_inclusion_of :transportation, :in => ["Private", "Nu buses"]
  validates :national_id, :format => {:with => /^[0-9]*$/ , :message => "Invalid Number"}
  validates :passport_number, :format => {:with => /^[0-9a-zA-Z]*$/ , :message => "Invalid Number"}
  validates_uniqueness_of :national_id, :case_sensitive => false, :message => "National ID has already been taken", :allow_blank => true
  validates_uniqueness_of :passport_number, :case_sensitive => false, :message => "Passport Number has already been taken", :allow_blank => true
  
  validates :country_of_issuance, inclusion: { in: ActionView::Helpers::FormOptionsHelper::COUNTRIES }, :allow_blank => true
  
  #CONTINUE VALIDATION  
  
  #validate :passport_must_be_unique
  #validate :national_must_be_unique

  #def passport_must_be_unique
  #  return if passport_number.blank?
  #  num_duplicates = self.class.count(:conditions => ["passport_number = ?", passport_number])
  #  if num_duplicates > 1 #not 0 because i already saved it..
  #    errors.add(:passport_number, :taken)
  #  end
  #end
  
  #def national_must_be_unique
  #  return if national_id.blank?
  #  num_duplicates = Applicant.count(:conditions => ["national_id = ?", national_id])
  #  logger.debug "National COUNT!!!!!!!!!!!!!!"
  #  logger.debug num_duplicates
  #  if num_duplicates > 1 #not 0 because i already saved it.. 
  #    errors.add(:national_id, :taken)
  #  end
  #end
  
  
  attr_writer :current_step
  accepts_nested_attributes_for :addresses
  accepts_nested_attributes_for :admission_information,  :guardians, :attachment,  :uni_related_info 
  accepts_nested_attributes_for :colleges,:secondary_schools,:healths, :allow_destroy => true
  # attr_accessor :reasons
  # attr_accessor :reasons2
  # attr_accessor :checkSecondary
  # attr_accessor :checkCollege
  # attr_accessor :checkWork
  
  #validates_presence_of :addresses, :message => "not exist in the DB"
  #validates_associated :addresses, :admission_information,:guardians, :secondary_schools, :colleges, :works, :attachment, :healths, :uni_related_info #,  :update
  validate :a_number_present
  validate :date_present
  validates_associated :addresses,:guardians, :secondary_schools, :healths #,  :update
  
  def to_s
    return "#{first_name} #{last_name}"
  end
  
  def display_name
    return "#{first_name} #{last_name}"
  end
  
  def a_number_present 
    errors.add(:national_id, "can't be blank") if national_id.blank? && passport_number.blank? 
    errors.add(:passport_number, "can't be blank") if national_id.blank? && passport_number.blank? 
  end
  
  def date_present 
  end
  
  def atleast_one
    logger.debug "address sizeeeee s333333333333333333333333333333333333333333333333333"
    logger.debug addresses
  end
    
  def current_step
    @current_step || steps.first
  end
  
  def steps
    %w[applicant address admission_information]
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end
  
  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end
  
  def first_step?
    current_step == steps.first
  end
  
  def last_step?
    current_step == steps.last
  end

   
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
   before_filter :authenticate_user!, :except => [:get_semester]
   before_filter :correct_user, :only => [:edit, :update, :show, :destroy]
   
  # def index
#     
    # @applications =  Applicant.order('created_at DESC').page params[:page]
#   
    # respond_to do |format|
      # format.html # index.html.erb
      # format.json { render json: @applications }
    # end
#     
  # end
  
  def instance
    @applicant = Applicant.find(params[:id])
  end

  def new
    #session[:applicant_params] ||= {}
    if flash[:flag]== true
      logger.debug "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    #logger.debug @flag
    logger.debug flash[:flag]
    
    
    @user=User.find(current_user.id)
    
    #don't need to write anything here, since it creates (new+save) in the create action
    @applicant = @user.build_applicant
    
    @applicant.healths.build
    @applicant.secondary_schools.build 
    @applicant.colleges.build
    #2.times do
    
    #end
   
    1.times do
      @applicant.addresses.build
      @applicant.guardians.build
      
    end
    
    @applicant.admission_information= AdmissionInformation.new
    @applicant.attachment = Attachment.new
    @applicant.uni_related_info = UniRelatedInfo.new
    
    @applicant.uni_related_info.uni_choice= UniChoice.new
    @applicant.uni_related_info.other_choice= OtherChoice.new
    
    #logger.debug "in new action"
    #logger.debug(@applicant.addresses)
     
    else
      redirect_to root_path,:notice => "redirected to root"
      
    end
    
    
  end

  def create
    
     @user=User.find(current_user.id)
     @applicant= @user.build_applicant(params[:applicant])
     
     
    if Semester.where(:status => true).count==0 || School.where(:status => true).count==0 
      redirect_to @user, notice: 'Sorry, Admission Closed.'
      
    else
     #@applicant = Applicant.new( params[:applicant] )
     #logger.debug "Applicant isssssssssssssss"
     #logger.debug @applicant.attributes
     #parameters=params[:applicant][:guardian_attributes]
     #logger.debug "Guardian Attributes!!!!!!!!!!!!!!"
     # if params[:applicant][:checkSecondary][:oneSchool]=="1"
      # @school='checked'
     # end
     #logger.debug ""
     
     #Saving here, to save the image incase submission fails
     #To save image
     @applicant.save(:validate => false)
     
     
     
     @applicant.guardians.each do |guardian|
       guardian.relation3=guardian.relation
       if guardian.relation=="Other"
         guardian.relation=guardian.relation2
       end
     end
     
     # logger.debug "Reasons!!!!!!!!"
     # logger.debug params[:applicant][:reasons]
     # logger.debug "Reasons2222!!!!!!!!"
     # logger.debug params[:applicant][:reasons2]
#      
     # @reasons="" 
     # params[:applicant][:reasons].each do |parameter, value|
       # if value == "1"
         # @reasons<<"#{parameter} "
       # end
       # if value != "0" and value != "1" and value != ""
         # @reasons<<"#{value} "
       # end
     # end 
#      
     # logger.debug "reasons"
     # logger.debug @reasons
#      
     # @reasons2="" 
     # params[:applicant][:reasons2].each do |parameter, value|
       # if value == "1"
         # @reasons2<<"#{parameter} "
       # end
       # if value != "0" and value != "1" and value != ""
         # @reasons2<<"#{value} "
       # end
     # end 
     
     @reasons="" 
     @reasons<<"Internet \n" if @applicant.uni_related_info.uni_choice.internet
     @reasons<<"Email \n" if @applicant.uni_related_info.uni_choice.email
     @reasons<<"Radio \n" if @applicant.uni_related_info.uni_choice.radio
     @reasons<<"School Visits \n" if @applicant.uni_related_info.uni_choice.school_visits
     @reasons<<"Nile University faculty/staff \n " if @applicant.uni_related_info.uni_choice.nile_university_faculty_and_staff
     @reasons<<"Nile University Student/Alumni \n" if @applicant.uni_related_info.uni_choice.nile_university_student_and_alumni
     @reasons<<"Print Advertisements " if @applicant.uni_related_info.uni_choice.print_advertisements
     @reasons<<"#{@applicant.uni_related_info.uni_choice.specify_print_advertisements} \n" if @applicant.uni_related_info.uni_choice.specify_print_advertisements != nil
     @reasons<<"NU Seminar, Workshop and Conference " if @applicant.uni_related_info.uni_choice.nu_seminar_workshop_and_conference
     @reasons<<"#{@applicant.uni_related_info.uni_choice.specify_nu_seminar} \n" if @applicant.uni_related_info.uni_choice.specify_nu_seminar != nil
     @reasons<<"Other " if @applicant.uni_related_info.uni_choice.other
     @reasons<<"#{@applicant.uni_related_info.uni_choice.specify_other} \n" if @applicant.uni_related_info.uni_choice.specify_other != nil
     
     
     
     @applicant.uni_related_info.hear_of_uni=@reasons
     

     
     
     # if @applicant.secondary_schools.size == 2
       # if @applicant.secondary_schools[0].id > @applicant.secondary_schools[1].id 
         # @temp= @applicant.secondary_schools[0]
         # @applicant.secondary_schools[0]= @applicant.secondary_schools[1]
         # @applicant.secondary_schools[1]= @temp
       # end
     # end
     
     
     
     #@applicant.guardians[0].relation="Mother"
     #logger.debug @applicant.guardians[0].relation
      if params[:save]
        @applicant.status="Saved"
        
        respond_to do |format|
        if @applicant.save(:validate => false)
          format.html { redirect_to @user.applicant, notice: 'Applicant was successfully created.' }
          format.json { render json: @applicant, status: :created, location: @applicant }
        else
          format.html { render action: "new" }
          format.json { render json: @applicant.errors, status: :unprocessable_entity }
        end
      end
      elsif params[:cont]
        @applicant.status="Saved"
        respond_to do |format|
        if @applicant.save(:validate => false)         
          format.html { redirect_to edit_applicant_path(@applicant), notice: 'Saved' }
         end      
      end
   else
    
     #before validation..
     # delete extra address
     logger.debug "Before Validation"
     
        # delete extra secondary schools
     # if @applicant.checkSecondary
       # @b=@applicant.secondary_schools[1]
       # if @b != nil
         # @applicant.secondary_schools.destroy(@b)
       # end
     # end
#      
     # # delete extra Colleges 
     # if @applicant.checkCollege
       # @b=@applicant.colleges[1]
       # if @b != nil
         # @applicant.colleges.destroy(@b)
       # end
     # end
#      
       
     
     logger.debug @applicant.addresses    
     logger.debug "checking!!!!!!!!!!!!!!!!!!!!!!!"
    #logger.debug params[:applicant][:checkSecondary][:oneSchool]
    @applicant.status="Submitted"
    logger.debug @user.attributes
    
      respond_to do |format|
        if @applicant.save
          
          html = render_to_string(:layout => false , :action => "show.html.erb")
          kit = PDFKit.new(html)
          kit.stylesheets << "#{Rails.root}/public/stylesheets/style2.css"
          email= kit.to_pdf
          
          ApplicationNotifier.submitted(@applicant.user,email).deliver
          format.html { redirect_to @user.applicant, notice: 'Applicant was successfully created.' }
          format.json { render json: @applicant, status: :created, location: @applicant }
        else
          #@user.save(:validate => false)
          logger.debug "ERRORS IN NEW!!!!!!!!!!"
          logger.debug @user.errors
          #error was becasue of password.. so instead saving applicant, since don't need to save user.
          @user.errors.each{|attr,msg| logger.debug "#{attr} - #{msg}" } 
          format.html { render action: "new", notice: "errorrrrrrrrrrr" }
          format.json { render json: @applicant.errors, status: :unprocessable_entity }
        end
      end
     end
    end
  end
  def edit
    logger.debug "IN EDIT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    @applicant = Applicant.find(params[:id])
    if @applicant.closed==true or @applicant.status=="Approved" or @applicant.status=="Rejected" or Semester.where(:status => true).count==0 or School.where(:status => true).count==0
      redirect_to @applicant, notice: "Sorry Admission Closed"
    end
    @applicant.guardians.each do |guardian|
       guardian.relation3=guardian.relation
       if guardian.relation!="Mother" and guardian.relation!="Father"
         guardian.relation3="Other"
       end
     end
     
  end
  
  def update
    
    
    @user=User.find(current_user.id)
    #@applicant= @user.build_applicant(params[:applicant])
    @applicant=@user.applicant 
    
    if @applicant.closed== true or @applicant.status=="Approved" or @applicant.status=="Rejected" or Semester.where(:status => true).count==0 or School.where(:status => true).count==0
      redirect_to @user.applicant, notice: 'Sorry, Admission Closed.'
      logger.debug "in here in update condition!!!!!"
    else
     
    #@applicant = Applicant.find(params[:id])
    #logger.debug "GENDERRRRRRRRRRRRRRR"
    #logger.debug params[:applicant]
    #logger.debug "GENDER AFTER CAST"
    #params[:applicant][:gender]=params[:applicant][:gender].to_i
    #logger.debug params[:applicant]
    
    # if params[:applicant][:checkSecondary][:oneSchool]=="1"
      # @school='checked'
    # end
    
    
    @applicant.attributes=params[:applicant]
    

    #To save image
    @applicant.save(:validate => false)
    
    @applicant.guardians.each do |guardian|
       guardian.relation3=guardian.relation
       if guardian.relation=="Other"
         guardian.relation=guardian.relation2
       end
     end
     
    
     
       
     @reasons="" 
     @reasons<<"Internet \n" if @applicant.uni_related_info.uni_choice.internet
     @reasons<<"Email \n" if @applicant.uni_related_info.uni_choice.email
     @reasons<<"Radio \n" if @applicant.uni_related_info.uni_choice.radio

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/create.html.erb
<h1>Applicants#create</h1>
<p>Find me in app/views/applicants/create.html.erb</p>

app/views/applicants/destroy.html.erb
<h1>Applicants#destroy</h1>
<p>Find me in app/views/applicants/destroy.html.erb</p>

app/views/applicants/show.html.erb
<p id="notice" align="center" style="color:#1C6CB7; font-size: 16px;">
	<%= notice %>
</p>
<p id="remove" align="center" style="padding-top:5px; padding-bottom: 10px;">
<%= link_to 'Edit Application', edit_applicant_path(@applicant), :class => 'btn btn-primary btn-large', :id => "edit", :style=>'width:200px'%> 
&nbsp; &nbsp;
<%= link_to 'Download Application (PDF)', applicant_path(@applicant, :format => "pdf"), :class => 'btn btn-primary btn-large', :id=>"pdf_link", :style=>'width:200px'%> 

</p>
<h2 style="font-size: 30px; color:#999999;">Applicant Info</h2>
<div class="well">
	<table class="table">
		<thead>
			<tr id="remove">
				<th><b>Photo</b></th>
				<% if @applicant.photo.file? %>
				<th><%= link_to image_tag(@applicant.photo.url(:thumb)), @applicant.photo.url %></th>
				<% else %>
				<th>You have not uploaded a photo</th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>First Name</b></td>
				<td><%= @applicant.first_name %></td>
			</tr>
			<tr>
				<td><b>Middle Name</b></td>
				<td><%= @applicant.middle_name %></td>
			</tr>
			<tr>
				<td><b>Last Name</b></td>
				<td><%= @applicant.last_name %></td>
			</tr>
			<tr>
				<td><b>Date of Birth</b></td>
				<td><%= @applicant.date_of_birth %></td>
			</tr>
			<tr>
				<td><b>Place of Birth</b></td>
				<td><%= @applicant.place_of_birth %></td>
			</tr>
			<tr>
				<td><b>Gender</b></td>
				<td><%= @applicant.gender %></td>
			</tr>
			<tr>
				<td><b>National ID</b></td>
				<td><%= @applicant.national_id %></td>
			</tr>
			<tr>
				<td><b>Passport Number</b></td>
				<td><%= @applicant.passport_number %></td>
			</tr>
			<tr>
				<td><b>Country of Issuance</b></td>
				<td><%= @applicant.country_of_issuance %></td>
			</tr>
			<tr>
				<td><b>Passport Expiry Date</b></td>
				<td><%= @applicant.passport_expiry_date %></td>
			</tr>
		</tbody>
	</table>
</div>
<h2 style="font-size: 30px; color:#999999;">Address</h2>
<div class="well">
	<% @applicant.addresses.each do |address|%>
	<table class="table">
		<thead>
			<tr>
				<td><b>Address</b></td>
				<td> <%= address.address %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Telephone</b></td>
				<td><%= address.telephone %></td>
			</tr>
			<tr>
				<td><b>Mobile:</b></td>
				<td><%= address.mobile %></td>
			</tr>		
		</tbody>
	</table>
	<% end %>
</div>
<h2 style="font-size: 30px; color:#999999;">Admission Information</h2>
<div class="well">
	<table class="table">
		<thead>
			<tr>
				<td><b>Semester</b></td>
				<td> 
					<% if @applicant.admission_information.semester!= nil %> 
					<%= @applicant.admission_information.semester.name %>
					<% end %>
				</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Applying To</b></td>
				<td>
					<% if @applicant.admission_information.school!= nil %> 
					<%= @applicant.admission_information.school.name %>
					<% end %>
				</td>
			</tr>
			<tr>
				<td><b>Intended Major</b></td>
				<td>
					<% if @applicant.admission_information.major!= nil %> 
					<%= @applicant.admission_information.major.name %>
					<% end %>
				</td>
			</tr>
			<tr>
				<td><b>Toefl Test Date</b></td>
				<td><%= @applicant.admission_information.toefl_test_date %></td>
			</tr>
			<tr>
				<td><b>Toefl Test Results</b></td>
				<td> <%= @applicant.admission_information.toefl_test_results %></td>
			</tr>
		</tbody>
	</table>
</div>

<h2 style="font-size: 30px; color:#999999;">Guardians</h2>
<div class="well">
<% @applicant.guardians.each do |guardian|%>
	<table class="table">
		<thead>
			<tr>
	  <td><b>First Name</b></td>
	  <td><%= guardian.first_name %></td>
	</tr>
	</thead>
	<tbody>
	<tr>
	  <td><b>Middle Name</b></td>
	  <td><%= guardian.middle_name %></td>
	</tr>	
	<tr>
	  <td><b>Last Name</b></td>
	  <td><%= guardian.last_name %></td>
	</tr>	
	<tr>
	  <td><b>Address</b></td>
	  <td><%= guardian.address %></td>
	</tr>	
	<tr>
	  <td><b>Telephone:</b></td>
	  <td><%= guardian.telephone %></td>
	</tr>	
	<tr>
	<td> <b>Mobile</b></td>
	 <td> <%= guardian.mobile %></td>
	</tr>	
	<tr>
	  <td><b>Occupation</b></td>
	  <td><%= guardian.occupation %></td>
	</tr>	
	<tr>
	  <td><b>Email</b></td>
	  <td><%= guardian.email %></td>
	</tr>	
	<tr>
	  <td><b>Relationship</b></td>
	  <td><%= guardian.relation %></td>
	</tr>	
	<tr>
	  <td><b>Paying for financial expenses</b></td>
	  <td><%= guardian.financial %></td>
	</tr>
	</tbody>		
	</table>
<% end %>
</div>

<h2 style="font-size: 30px; color:#999999;">Secondary Schools</h2>
<div class="well">
	<% @applicant.secondary_schools.each do |school|%>
	<table class="table">
		<thead>
			<tr>
				<td><b>Name</b></td>
				<td><%= school.name %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Address</b></td>
				<td><%= school.address %></td>
			</tr>
			<tr>
				<td><b>Language</b></td>
				<td><%= school.language %></td>
			</tr>
			<tr>
				<td><b>Attended From</b></td>
				<td><%= school.attended_from %></td>
			</tr>
			<tr>
				<td><b>Attended To</b></td>
				<td><%= school.attended_to %></td>
			</tr>
			<tr>
				<td><b>Certificate Type</b></td>
				<td><%= school.certificate_type %></td>
			</tr>
			<tr>
				<td><b>Graduation Date</b></td>
				<td><%= school.graduation_date %></td>
			</tr>
			<tr>
				<td><b>Division</b></td>
				<td><%= school.division %></td>
			</tr>
			<tr>
				<td><b>School Type</b></td>
				<td><%= school.school_type %></td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>

<% if @applicant.colleges!=nil and @applicant.colleges.size > 0 %>
<h2 style="font-size: 30px; color:#999999;">Colleges</h2>
<div class="well">
	<% @applicant.colleges.each do |college|%>
	<table class="table">
		<thead>
			<tr>
				<td><b>Name</b></td>
				<td><%= college.name %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Faculty</b></td>
				<td><%= college.faculty %></td>
			</tr>
			<tr>
				<td><b>Major</b></td>
				<td><%= college.major %></td>
			</tr>
			<tr>
				<td><b>City</b></td>
				<td><%= college.city %></td>
			</tr>
			<tr>
				<td><b>Country</b></td>
				<td><%= college.country %></td>
			</tr>
			<tr>
				<td><b>Attended From</b></td>
				<td><%= college.attended_from %></td>
			</tr>
			<tr>
				<td><b>Attended To</b></td>
				<td><%= college.attended_to %></td>
			</tr>
			<tr>
				<td><b>Language</b></td>
				<td><%= college.language %></td>
			</tr>
			<tr>
				<td><b>GPA</b></td>
				<td><%= college.gpa %></td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>
<% end %>


<% if @applicant.healths!=nil and @applicant.healths.size > 0 %>
<h2 style="font-size: 30px; color:#999999;">Health</h2>
<div class="well">
	<% @applicant.healths.each do |health|%>
	<table class="table">
		<thead>
			<tr>
				<td><b>Illness</b></td>
				<td><%= health.illness %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Description</b></td>
				<td><%= health.description %></td>
			</tr>
		</tbody>
	</table>
	<% end %>
</div>
<% end %>

<h2 style="font-size: 30px; color:#999999;">University Related Information</h2>
<div class="well">
	<table class="table">
		<thead>
			<tr>
				<td><b>How did you hear of Nile University?</b></td>
				<td><%= @applicant.uni_related_info.hear_of_uni %></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><b>Transportation</b></td>
				<td><%= @applicant.transportation %></td>
			</tr>
		</tbody>
	</table>
</div>

<h2 id="remove" style="font-size: 30px; color:#999999;">Attachments</h2>
<div id="remove" class="well">
	<table class="table">
		<thead>
			<tr>
				<div>
					<td><b>Additional Information</b></td>
					<% if @applicant.attachment.additional_information.file? %>
					<td><%= link_to image_tag(@applicant.attachment.additional_information.url(:thumb)), @applicant.attachment.additional_information.url %></td>
					<% else %>
					<td><b> You have not uploaded the additional information document</b></td>
					<% end %>
				</div>
			</tr>
		</thead>
		<tbody>
			<tr>
				<div>
					
					
					<td><b>Personal Experience</b></td>
					<% if @applicant.attachment.personal_experience.file? %>
					<td><%= link_to image_tag(@applicant.attachment.personal_experience.url(:thumb)), @applicant.attachment.personal_experience.url %></td>
					<% else %>
					<td><b> You have not uploaded the personal experience document</b></td>
					<% end %>
					<!-- <%= link_to "Download", @applicant.attachment.personal_experience.url %> -->
					
					
				</div>
			</tr>
			
		</tbody>
		<tbody>
			<tr>
				<div>
					
					
					<td><b>School Certificates</b></td>
					<% if @applicant.attachment.school_certificates.file? %>
					<td><%= link_to image_tag(@applicant.attachment.school_certificates.url(:thumb)), @applicant.attachment.school_certificates.url %></td>
					<% else %>
					<td><b> You have not uploaded your school certificates</b></td>
					<% end %>
					<!-- <%= link_to "Download", @applicant.attachment.personal_experience.url %> -->
					
					
				</div>
			</tr>
			
		</tbody>
	</table>
</div>

<p id="remove" align="center" style="padding-top:50px; padding-bottom: 190px;">
<%= link_to 'Edit Application', edit_applicant_path(@applicant), :class => 'btn btn-primary btn-large', :id => "edit", :style=>'width:200px'%> 
&nbsp; &nbsp;
<%= link_to 'Download Application (PDF)', applicant_path(@applicant, :format => "pdf"), :class => 'btn btn-primary btn-large', :id=>"pdf_link", :style=>'width:200px'%> 

</p>








<!-- <%= link_to "Download PDF", instance_applicant_path(@applicant.id, :format => "pdf") %>
<%= link_to 'PDF', applicant_path(@applicant, :format => "pdf") %> -->
<!--
<p id="pdf_link"><%= link_to "Download Application (PDF)", applicant_path(@applicant, :format => "pdf") %></p>
--> 