config/routes.rb
Admission::Application.routes.draw do
  
 
  devise_for :users

  get "home/index"

  root :to => "home#index"

  resources :users do
      member do
        get 'application'
      end
    end
    
  match 'user_root' => 'users#move', as: :user_root

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :applicants do 
    member do
      get 'instance'
    end
    collection do
      get 'update_major_select'
      get 'get_semester'
    end
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_one :applicant, :dependent => :destroy
  
  #attr_accessible :email, :password, :password_confirmation
  #to limit mass assignment to email, password and password_confirmation, to prevent anyone from changing
  # the password hash or the salt..
  
  # attr_accessor :password #since not defined in model.. not in table.
  # before_save :encrypt_password
#   
  # validates_confirmation_of :password #automatically adds password confirmation attribute
  # validates_presence_of :password, :on => :create
  # validates :password,
          # :length => { :within => 6..40 }
  # validates_presence_of :email
  # validates_uniqueness_of :email, :case_sensitive => false, :message => "Email has already taken"
  # validates :email, :format => {:with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, :message => "Invalid E-mail"}
#   
  accepts_nested_attributes_for :applicant
  
  def to_s
    email
  end
  
  # def self.authenticate(email, password) #class method
    # #user = find_by_email(email)
    # user= find(:all, :conditions => [ "lower(email) = ?", email.downcase ]).first
    # if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      # user
    # else
      # nil
    # end
  # end
#   
  # def encrypt_password
    # if password.present?
      # self.password_salt = BCrypt::Engine.generate_salt
      # self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    # end
  # end
  after_create :send_welcome_mail
  
  def send_welcome_mail
     ApplicationNotifier.created(self).deliver
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #skip_before_filter :authorize
  before_filter :correct_user2, :only => [:show, :application]
  
  # def new
    # @user = User.new
    # if session[:user_id]!= nil
      # @existing=User.find(session[:user_id])
      # redirect_to @existing , notice: "#{@existing.email} is already logged in, Please Log out first"
    # end
  # end
  
  

  # def create
    # @user = User.new(params[:user])
    # if @user.save
      # session[:user_id] = @user.id  #to save in session..
      # ApplicationNotifier.created(@user).deliver
      # redirect_to @user, :notice => "Signed up!"
    # else
      # render "new"
    # end
  # end

  
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
  def move
    redirect_to user_path(:id => current_user.id)
  end
  
  def application  #ADJUST THIS!!!!   
    @user = User.find(params[:id])
    if Semester.where(:status => true).count>0 and School.where(:status => true).count>0
      if @user.applicant == nil
        flash[:flag]=true
        redirect_to new_applicant_url
      else
        redirect_to @user.applicant,:notice => "applicant exists"
      end
    else
       redirect_to @user, :notice => "Admission Closed"
    end
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/new.html.erb
<div class="sign_up_bg">
	<h2>Sign Up</h2>
	<div class="sign_up">
		<%= form_for @user, :validate => true do |f| %>
		<!-- <% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
				<li>
					<%= message %>
				</li>
				<% end %>
			</ul>
		</div>
		<% end %> -->
		<p>
			<%= f.label :email%> <%= mark_required(@user, :email) %>
			<!--<%= image_tag ('required-star.gif'),{:height => 9, :width => 10, :class=>'required'} %>-->

			<br />
			<%= f.text_field :email, {:class => 'span2', :placeholder => "example@example.com"}%>
		</p>
		<p>
			<%= f.label :password %><%= mark_required(@user, :password) %>
			<br />
			<%= f.password_field :password, {:class => 'span2'}  %>
		</p>
		<p>
			<%= f.label :password_confirmation, "Confirm Password" %><%= mark_required(@user, :password) %>
			<br />
			<%= f.password_field :password_confirmation, {:class => 'span2'} %>
		</p>
		<p>
			<%= f.submit :class => 'btn'%>
		</p>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice" align="center">
	
	Welcome <%= @user.email %><br /><br />
	<%= notice %>
</p>
<p align="center" style="padding-top:50px; padding-bottom: 190px;">
<%= link_to 'Application', application_user_url, :class => 'btn btn-primary btn-large'%>
<!-- <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-primary btn-large' %> 
<%= link_to 'Back', users_path, :class => 'btn btn-primary btn-large' %> --></p>